const GENRE_ID_UNIT = 100;
const AUTHOR_ID_UNIT = 1000;
const WEBTOON_ID_UNIT = 10000;
const COLLECTION_ID_UNIT = 100000;

export { GENRE_ID_UNIT, AUTHOR_ID_UNIT, WEBTOON_ID_UNIT, COLLECTION_ID_UNIT };
